"use client";

import { useEffect, useMemo, useState } from "react";

export type Lang = "en" | "ar" | "fr" | "de" | "ko" | "pt" | "es" | "vi";
type LocalizedFields = Partial<Record<Lang, { title?: string; body?: string; meta?: string }>>;
type Update = { id: number; section: string; title: string; body: string; meta: string; translations?: LocalizedFields | string | null; imageUrl?: string | null; updatedBy: string; createdAt: string };
type BoardData = { sections: Record<string, Update[]>; updatedAt: string | null };

const languages: { code: Lang; name: string; locale: string }[] = [
  { code: "en", name: "English", locale: "en" }, { code: "ar", name: "العربية", locale: "ar" },
  { code: "fr", name: "Français", locale: "fr" }, { code: "de", name: "Deutsch", locale: "de" },
  { code: "ko", name: "한국어", locale: "ko" }, { code: "pt", name: "Português", locale: "pt" },
  { code: "es", name: "Español", locale: "es" }, { code: "vi", name: "Tiếng Việt", locale: "vi" },
];

const copy: Record<Lang, Record<string, string>> = {
  en: { welcome: "Welcome home, Sapphire", hello: "Hello, Nova!", ready: "Ready for today?", intro: "Everything we need for a strong day—tasks, trains, strategy, celebrations, and just enough chaos.", tasks: "Today's Shiny Tasks", captures: "Upcoming Captures", strategy: "Weekly VS Strategy", battle: "Next Battle Day", meme: "Meme of the Week", train: "All Aboard!", hammer: "Golden Hammer", spotlight: "Sapphire Spotlight", live: "Alliance board is live", bulletin: "Bulletin", updated: "Updated", sample: "Sample board", loading: "Loading the latest bulletin…", language: "Choose a language", dragon: "Cheerful red dragon", footer: "Made with ✦ for Nova Sapphire · Server 1616", discord: "Updates powered by Discord", unavailable: "Live updates are temporarily unavailable." },
  ar: { welcome: "أهلاً بعودتك يا Sapphire", hello: "مرحباً، Nova!", ready: "هل أنتم مستعدون لليوم؟", intro: "كل ما نحتاجه ليوم قوي: المهام والقطارات والاستراتيجية والاحتفالات وقليل من الفوضى.", tasks: "مهام اليوم اللامعة", captures: "عمليات الاستيلاء القادمة", strategy: "استراتيجية VS الأسبوعية", battle: "يوم المعركة القادم", meme: "ميم الأسبوع", train: "الجميع على متن القطار!", hammer: "المطرقة الذهبية", spotlight: "نجوم Sapphire", live: "لوحة التحالف مباشرة", bulletin: "نشرة", updated: "آخر تحديث", sample: "لوحة تجريبية", loading: "جارٍ تحميل أحدث نشرة…", language: "اختر اللغة", dragon: "تنين أحمر مرح", footer: "صُنع بحب ✦ لتحالف Nova Sapphire · الخادم 1616", discord: "التحديثات عبر Discord", unavailable: "التحديثات المباشرة غير متاحة مؤقتاً." },
  fr: { welcome: "Bienvenue chez toi, Sapphire", hello: "Bonjour, Nova !", ready: "Prêts pour aujourd'hui ?", intro: "Tout ce qu’il faut pour une belle journée : tâches, trains, stratégie, célébrations et juste assez de chaos.", tasks: "Les tâches brillantes du jour", captures: "Prochaines captures", strategy: "Stratégie VS de la semaine", battle: "Prochain jour de bataille", meme: "Mème de la semaine", train: "En voiture !", hammer: "Marteau doré", spotlight: "Sous les projecteurs", live: "Le tableau est à jour", bulletin: "Bulletin", updated: "Mis à jour", sample: "Tableau de démonstration", loading: "Chargement du dernier bulletin…", language: "Choisir une langue", dragon: "Joyeux dragon rouge", footer: "Créé avec ✦ pour Nova Sapphire · Serveur 1616", discord: "Mises à jour via Discord", unavailable: "Les mises à jour en direct sont temporairement indisponibles." },
  de: { welcome: "Willkommen zu Hause, Sapphire", hello: "Hallo, Nova!", ready: "Bereit für heute?", intro: "Alles für einen starken Tag: Aufgaben, Züge, Strategie, Erfolge und genau genug Chaos.", tasks: "Heutige Glanzaufgaben", captures: "Kommende Eroberungen", strategy: "Wöchentliche VS-Strategie", battle: "Nächster Kampftag", meme: "Meme der Woche", train: "Alle einsteigen!", hammer: "Goldener Hammer", spotlight: "Sapphire-Rampenlicht", live: "Allianzbrett ist live", bulletin: "Meldung", updated: "Aktualisiert", sample: "Beispieltafel", loading: "Die neuesten Meldungen werden geladen…", language: "Sprache wählen", dragon: "Fröhlicher roter Drache", footer: "Mit ✦ für Nova Sapphire erstellt · Server 1616", discord: "Updates über Discord", unavailable: "Live-Updates sind vorübergehend nicht verfügbar." },
  ko: { welcome: "Sapphire, 돌아온 걸 환영해요", hello: "안녕하세요, Nova!", ready: "오늘도 준비됐나요?", intro: "강한 하루에 필요한 모든 것—임무, 열차, 전략, 축하 그리고 적당한 혼돈.", tasks: "오늘의 반짝 임무", captures: "예정된 도시 점령", strategy: "주간 VS 전략", battle: "다음 전투일", meme: "이번 주의 밈", train: "모두 탑승!", hammer: "골든 해머", spotlight: "Sapphire 스포트라이트", live: "연맹 게시판 라이브", bulletin: "알림", updated: "업데이트", sample: "예시 게시판", loading: "최신 소식을 불러오는 중…", language: "언어 선택", dragon: "명랑한 빨간 용", footer: "Nova Sapphire를 위해 ✦로 제작 · 서버 1616", discord: "Discord에서 업데이트", unavailable: "실시간 업데이트를 잠시 사용할 수 없습니다." },
  pt: { welcome: "Bem-vindos a casa, Sapphire", hello: "Olá, Nova!", ready: "Prontos para hoje?", intro: "Tudo para um ótimo dia: tarefas, trens, estratégia, celebrações e a quantidade certa de caos.", tasks: "Tarefas brilhantes de hoje", captures: "Próximas capturas", strategy: "Estratégia VS semanal", battle: "Próximo dia de batalha", meme: "Meme da semana", train: "Todos a bordo!", hammer: "Martelo Dourado", spotlight: "Destaque Sapphire", live: "Painel da aliança ao vivo", bulletin: "Boletim", updated: "Atualizado", sample: "Painel de exemplo", loading: "Carregando o boletim mais recente…", language: "Escolher idioma", dragon: "Dragão vermelho alegre", footer: "Feito com ✦ para Nova Sapphire · Servidor 1616", discord: "Atualizações via Discord", unavailable: "As atualizações ao vivo estão temporariamente indisponíveis." },
  es: { welcome: "Bienvenidos a casa, Sapphire", hello: "¡Hola, Nova!", ready: "¿Listos para hoy?", intro: "Todo lo necesario para un gran día: tareas, trenes, estrategia, celebraciones y la dosis justa de caos.", tasks: "Tareas brillantes de hoy", captures: "Próximas capturas", strategy: "Estrategia VS semanal", battle: "Próximo día de batalla", meme: "Meme de la semana", train: "¡Todos a bordo!", hammer: "Martillo Dorado", spotlight: "Momento Sapphire", live: "Tablón de la alianza activo", bulletin: "Boletín", updated: "Actualizado", sample: "Tablón de ejemplo", loading: "Cargando el boletín más reciente…", language: "Elegir idioma", dragon: "Dragón rojo alegre", footer: "Hecho con ✦ para Nova Sapphire · Servidor 1616", discord: "Actualizaciones desde Discord", unavailable: "Las actualizaciones en vivo no están disponibles temporalmente." },
  vi: { welcome: "Chào mừng về nhà, Sapphire", hello: "Xin chào, Nova!", ready: "Sẵn sàng cho hôm nay?", intro: "Mọi thứ cho một ngày mạnh mẽ—nhiệm vụ, tàu, chiến lược, ăn mừng và một chút hỗn loạn.", tasks: "Nhiệm vụ lấp lánh hôm nay", captures: "Chiếm thành sắp tới", strategy: "Chiến lược VS hàng tuần", battle: "Ngày chiến đấu tiếp theo", meme: "Meme của tuần", train: "Tất cả lên tàu!", hammer: "Búa Vàng", spotlight: "Tiêu điểm Sapphire", live: "Bảng liên minh đang hoạt động", bulletin: "Thông báo", updated: "Cập nhật", sample: "Bảng mẫu", loading: "Đang tải thông báo mới nhất…", language: "Chọn ngôn ngữ", dragon: "Chú rồng đỏ vui vẻ", footer: "Được tạo với ✦ cho Nova Sapphire · Máy chủ 1616", discord: "Cập nhật qua Discord", unavailable: "Bản cập nhật trực tiếp tạm thời không khả dụng." },
};

const translatedUpdate = (id: number, section: string, values: Record<Lang, [string, string, string]>): Update => ({
  id, section, title: values.en[0], body: values.en[1], meta: values.en[2], updatedBy: "Raid", createdAt: "",
  translations: Object.fromEntries(Object.entries(values).map(([language, value]) => [language, { title: value[0], body: value[1], meta: value[2] }])),
});

const row = (id: number, section: string, en: [string,string,string], ar: [string,string,string], fr: [string,string,string], de: [string,string,string], ko: [string,string,string], pt: [string,string,string], es: [string,string,string], vi: [string,string,string]) => translatedUpdate(id, section, { en, ar, fr, de, ko, pt, es, vi });

const fallback: Record<string, Update[]> = {
  bulletin: [row(0,"bulletin",["Great work in VS, Nova!","Save radar tasks after reset • City capture Saturday at 13:00 ST • Train leaves at 02:00 ST",""],["عمل رائع في VS يا Nova!","احفظ مهام الرادار بعد إعادة الضبط • الاستيلاء السبت 13:00 • القطار 02:00",""] ,["Excellent travail en VS, Nova !","Gardez les tâches radar • Capture samedi à 13:00 ST • Train à 02:00 ST",""] ,["Starke Arbeit im VS, Nova!","Radaraufgaben aufheben • Eroberung Samstag 13:00 ST • Zug 02:00 ST",""] ,["VS에서 잘했어요, Nova!","레이더 임무 저장 • 토요일 13:00 ST 도시 점령 • 02:00 ST 열차",""] ,["Ótimo trabalho no VS, Nova!","Guarde as tarefas de radar • Captura sábado às 13:00 ST • Trem às 02:00 ST",""] ,["¡Gran trabajo en VS, Nova!","Guarda las tareas de radar • Captura el sábado a las 13:00 ST • Tren a las 02:00 ST",""] ,["Làm tốt lắm trong VS, Nova!","Để dành nhiệm vụ radar • Chiếm thành thứ Bảy 13:00 ST • Tàu 02:00 ST",""])],
  tasks: [
    row(1,"tasks",["Complete radar tasks","Save the final one for tomorrow",""],["أكمل مهام الرادار","احفظ المهمة الأخيرة للغد",""] ,["Terminer les tâches radar","Gardez la dernière pour demain",""] ,["Radaraufgaben abschließen","Die letzte für morgen aufheben",""] ,["레이더 임무 완료","마지막 하나는 내일을 위해 저장",""] ,["Concluir tarefas de radar","Guarde a última para amanhã",""] ,["Completa las tareas de radar","Guarda la última para mañana",""] ,["Hoàn thành nhiệm vụ radar","Để dành nhiệm vụ cuối cho ngày mai",""]),
    row(2,"tasks",["Donate 5,000 alliance points","Tech tree: Season Development",""],["تبرع بـ 5,000 نقطة تحالف","شجرة التقنية: تطوير الموسم",""] ,["Donner 5 000 points d’alliance","Arbre techno : Développement de saison",""] ,["5.000 Allianzpunkte spenden","Technologiebaum: Saisonentwicklung",""] ,["연맹 포인트 5,000 기부","기술 트리: 시즌 개발",""] ,["Doar 5.000 pontos da aliança","Árvore tecnológica: Desenvolvimento da temporada",""] ,["Dona 5.000 puntos de alianza","Árbol tecnológico: Desarrollo de temporada",""] ,["Đóng góp 5.000 điểm liên minh","Cây công nghệ: Phát triển mùa",""]),
    row(3,"tasks",["Finish your three rallies","Illuminate before you launch",""],["أكمل حشودك الثلاثة","فعّل الإضاءة قبل الانطلاق",""] ,["Terminer vos trois ralliements","Illuminez avant de lancer",""] ,["Drei Rallyes abschließen","Vor dem Start beleuchten",""] ,["집결 세 번 완료","출발 전 일루미네이트 사용",""] ,["Concluir seus três comícios","Ilumine antes de iniciar",""] ,["Completa tus tres concentraciones","Ilumina antes de lanzarlas",""] ,["Hoàn thành ba cuộc tập kết","Chiếu sáng trước khi khởi động",""]),
  ],
  captures:[row(4,"captures",["Frosthaven","13:00 Server Time","SEP 19 · LV. 6"],["Frosthaven","13:00 بتوقيت الخادم","19 سبتمبر · المستوى 6"],["Frosthaven","13:00, heure du serveur","19 SEPT. · NIV. 6"],["Frosthaven","13:00 Serverzeit","19. SEP. · ST. 6"],["Frosthaven","서버 시간 13:00","9월 19일 · 레벨 6"],["Frosthaven","13:00, horário do servidor","19 SET · NV. 6"],["Frosthaven","13:00, hora del servidor","19 SEP · NIV. 6"],["Frosthaven","13:00 giờ máy chủ","19 THG 9 · CẤP 6"])],
  strategy:[row(5,"strategy",["WIN WEEK","Radar · Build · Research · Heroes · Troops · Combat · Save","Tap a day to see its focus"],["أسبوع الفوز","رادار · بناء · بحث · أبطال · قوات · قتال · ادخار","اضغط على اليوم لمعرفة التركيز"],["SEMAINE DE VICTOIRE","Radar · Construction · Recherche · Héros · Troupes · Combat · Épargne","Touchez un jour pour voir son objectif"],["SIEGWOCHE","Radar · Bauen · Forschen · Helden · Truppen · Kampf · Sparen","Tag antippen, um den Fokus zu sehen"],["승리 주간","레이더 · 건설 · 연구 · 영웅 · 병력 · 전투 · 저장","요일을 눌러 중점 확인"],["SEMANA DA VITÓRIA","Radar · Construção · Pesquisa · Heróis · Tropas · Combate · Guardar","Toque em um dia para ver o foco"],["SEMANA DE VICTORIA","Radar · Construcción · Investigación · Héroes · Tropas · Combate · Ahorro","Toca un día para ver el enfoque"],["TUẦN CHIẾN THẮNG","Radar · Xây dựng · Nghiên cứu · Anh hùng · Quân đội · Chiến đấu · Tích trữ","Chạm vào ngày để xem trọng tâm"])],
  battle:[row(6,"battle",["NvSP vs KNG","Saturday · 12:00 ST","Prepare shields and war fever"],["NvSP ضد KNG","السبت · 12:00 بتوقيت الخادم","جهّز الدروع وحمّى الحرب"],["NvSP contre KNG","Samedi · 12:00 ST","Préparez boucliers et fièvre de guerre"],["NvSP gegen KNG","Samstag · 12:00 ST","Schilde und Kriegsfieber vorbereiten"],["NvSP 대 KNG","토요일 · 12:00 ST","방패와 전쟁 열기 준비"],["NvSP x KNG","Sábado · 12:00 ST","Prepare escudos e febre de guerra"],["NvSP vs KNG","Sábado · 12:00 ST","Prepara escudos y fiebre de guerra"],["NvSP đấu KNG","Thứ Bảy · 12:00 ST","Chuẩn bị khiên và cơn sốt chiến tranh"])],
  meme:[row(7,"meme",["I’ll only log in for five minutes.","— every commander, three hours ago","Submitted by Raid"],["سأسجل الدخول لخمس دقائق فقط.","— كل قائد، قبل ثلاث ساعات","مقدم من Raid"],["Je me connecte seulement cinq minutes.","— chaque commandant, il y a trois heures","Proposé par Raid"],["Ich logge mich nur fünf Minuten ein.","— jeder Kommandant, vor drei Stunden","Eingereicht von Raid"],["5분만 접속할게요.","— 모든 지휘관, 세 시간 전","Raid 제보"],["Vou entrar só por cinco minutos.","— todo comandante, três horas atrás","Enviado por Raid"],["Solo entraré cinco minutos.","— cada comandante, hace tres horas","Enviado por Raid"],["Tôi chỉ đăng nhập năm phút thôi.","— mọi chỉ huy, ba giờ trước","Raid gửi"])],
  train:[row(8,"train",["Weekly Train","MON Fritz\nTUE SashLKA\nWED Mwgas\nTHU DookyKid\nFRI RaidARQN","02:00 Server Time"],["قطار الأسبوع","الاثنين Fritz\nالثلاثاء SashLKA\nالأربعاء Mwgas\nالخميس DookyKid\nالجمعة RaidARQN","02:00 بتوقيت الخادم"],["Train de la semaine","LUN Fritz\nMAR SashLKA\nMER Mwgas\nJEU DookyKid\nVEN RaidARQN","02:00, heure du serveur"],["Wochenzug","MO Fritz\nDI SashLKA\nMI Mwgas\nDO DookyKid\nFR RaidARQN","02:00 Serverzeit"],["주간 열차","월 Fritz\n화 SashLKA\n수 Mwgas\n목 DookyKid\n금 RaidARQN","서버 시간 02:00"],["Trem semanal","SEG Fritz\nTER SashLKA\nQUA Mwgas\nQUI DookyKid\nSEX RaidARQN","02:00, horário do servidor"],["Tren semanal","LUN Fritz\nMAR SashLKA\nMIÉ Mwgas\nJUE DookyKid\nVIE RaidARQN","02:00, hora del servidor"],["Tàu hàng tuần","T2 Fritz\nT3 SashLKA\nT4 Mwgas\nT5 DookyKid\nT6 RaidARQN","02:00 giờ máy chủ"])],
  hammer:[row(9,"hammer",["LazyBum","For being under the radar, quietly consistent, and incredibly helpful.","NOVA HERO"],["LazyBum","لعمله بهدوء وثبات ومساعدته الرائعة للجميع.","بطل NOVA"],["LazyBum","Pour sa constance discrète et son aide incroyable.","HÉROS NOVA"],["LazyBum","Für leise Beständigkeit und großartige Hilfsbereitschaft.","NOVA-HELD"],["LazyBum","눈에 띄지 않아도 꾸준하고 놀랍도록 도움을 주어서.","NOVA 영웅"],["LazyBum","Por manter a constância nos bastidores e ajudar de forma incrível.","HERÓI NOVA"],["LazyBum","Por su constancia silenciosa y su increíble ayuda.","HÉROE NOVA"],["LazyBum","Vì sự bền bỉ thầm lặng và tinh thần giúp đỡ tuyệt vời.","ANH HÙNG NOVA"])],
  spotlight:[row(10,"spotlight",["Big moments worth celebrating","Siluxx — HQ 33\nBánh Đậu Đỏ — 40M squad power\nLizardmercer — 10M kills",""],["لحظات كبيرة تستحق الاحتفال","Siluxx — المقر 33\nBánh Đậu Đỏ — قوة فرقة 40M\nLizardmercer — 10M قتيل",""],["De grands moments à célébrer","Siluxx — QG 33\nBánh Đậu Đỏ — 40 M de puissance\nLizardmercer — 10 M d’éliminations",""],["Große Momente zum Feiern","Siluxx — HQ 33\nBánh Đậu Đỏ — 40 Mio. Truppstärke\nLizardmercer — 10 Mio. Kills",""],["함께 축하할 멋진 순간","Siluxx — 본부 33\nBánh Đậu Đỏ — 분대 전투력 4천만\nLizardmercer — 처치 1천만",""],["Grandes momentos para comemorar","Siluxx — QG 33\nBánh Đậu Đỏ — 40M de poder\nLizardmercer — 10M de eliminações",""],["Grandes momentos para celebrar","Siluxx — CG 33\nBánh Đậu Đỏ — 40 M de poder\nLizardmercer — 10 M de bajas",""],["Những khoảnh khắc đáng ăn mừng","Siluxx — Trụ sở 33\nBánh Đậu Đỏ — 40M sức mạnh\nLizardmercer — 10M mạng",""])],
};

function translationsFor(item: Update): LocalizedFields {
  if (!item.translations) return {};
  if (typeof item.translations === "object") return item.translations;
  try { return JSON.parse(item.translations) as LocalizedFields; } catch { return {}; }
}

function translateItem(item: Update, lang: Lang): Update {
  const translations = translationsFor(item);
  const fields = translations[lang] ?? translations.en;
  return { ...item, title: fields?.title || item.title, body: fields?.body ?? item.body, meta: fields?.meta ?? item.meta };
}

function Card({ title, icon, section, items, character }: { title: string; icon: string; section: string; items: Update[]; character?: string }) {
  const first = items[0];
  return <section className={`card ${section}`}><header><span className="icon" aria-hidden="true">{icon}</span><div><h2>{title}</h2>{first?.meta && <small>{first.meta}</small>}</div></header><div className="entries">{items.map(item => <article className="entry" key={item.id}><strong>{item.title}</strong>{item.body && item.body.split("\n").map((line, i) => <p key={i}>{line}</p>)}{item.imageUrl && <img className="update-image" src={item.imageUrl} alt="" />}</article>)}</div>{character && <img className="character" src={character} alt="" />}</section>;
}

export default function NovaBoard() {
  const [lang, setLang] = useState<Lang>("en");
  const [data, setData] = useState<BoardData>({ sections: {}, updatedAt: null });
  const [loaded, setLoaded] = useState(false);
  const [loadError, setLoadError] = useState(false);
  useEffect(() => {
    const saved = localStorage.getItem("nova-lang") as Lang | null;
    if (saved && copy[saved]) setLang(saved);
    fetch("/api/board").then(response => response.ok ? response.json() : Promise.reject()).then(setData).catch(() => setLoadError(true)).finally(() => setLoaded(true));
  }, []);
  useEffect(() => { document.documentElement.lang = lang; document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"; }, [lang]);
  const sections = useMemo(() => {
    const merged = { ...fallback, ...data.sections };
    return Object.fromEntries(Object.entries(merged).map(([section, items]) => [section, items.map(item => translateItem(item, lang))]));
  }, [data, lang]);
  const t = copy[lang];
  const locale = languages.find(language => language.code === lang)?.locale ?? lang;
  const change = (value: Lang) => { setLang(value); localStorage.setItem("nova-lang", value); };
  const updated = data.updatedAt ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(data.updatedAt)) : t.sample;
  return <main className="shell" dir={lang === "ar" ? "rtl" : "ltr"}>
    <nav className="topbar" aria-label="Primary"><div className="brand"><span className="brandmark" aria-hidden="true">✦</span><div>THE NOVA NOOK<small>NOVA SAPPHIRE · 1616</small></div></div><div className="controls"><span className="live"><i aria-hidden="true" /> {t.live}</span><label className="language"><span className="sr-only">{t.language}</span><select aria-label={t.language} value={lang} onChange={event => change(event.target.value as Lang)}>{languages.map(({ code, name }) => <option key={code} value={code}>{name}</option>)}</select></label></div></nav>
    <section className="hero"><div><span className="eyebrow">✦ {t.welcome}</span><h1>{t.hello}<br /><em>{t.ready}</em></h1><p>{t.intro}</p><small aria-live="polite">{loadError ? t.unavailable : loaded ? `${t.updated}: ${updated}` : t.loading}</small></div><img src="/dragon.png" alt={t.dragon} /></section>
    <section className="ticker" aria-label={t.bulletin}><b>{t.bulletin}</b><div><strong>{sections.bulletin[0].title}</strong> · {sections.bulletin[0].body}</div></section>
    <div className="board"><div className="main-grid"><Card title={t.tasks} icon="✨" section="tasks" items={sections.tasks} /><Card title={t.captures} icon="🏰" section="captures" items={sections.captures} /><Card title={t.strategy} icon="⚡" section="strategy" items={sections.strategy} /><Card title={t.battle} icon="⚔️" section="battle" items={sections.battle} /><Card title={t.meme} icon="😆" section="meme" items={sections.meme} character="/tree.png" /></div><aside><Card title={t.train} icon="🚂" section="train" items={sections.train} character="/sushi.png" /><Card title={t.hammer} icon="🔨" section="hammer" items={sections.hammer} character="/octopus.png" /><Card title={t.spotlight} icon="🌸" section="spotlight" items={sections.spotlight} /></aside></div>
    <footer><span>{t.footer}</span><span>{t.discord}</span></footer>
  </main>;
}
